
/** 
 * This file generated by Apso.
*/

import LeadRepository from "../repositories/LeadRepository";
import { Config } from "../cfg";
import LandingPageRepository from "../repositories/LandingPageRepository";

export default class LeadService {
    private readonly leadRepo: LeadRepository;
    private readonly pageRepo: LandingPageRepository;
    private readonly config: Config;

    public constructor(
        /** LeadRepository */leadRepo: LeadRepository,
        /** LandingPageRepository */pageRepo: LandingPageRepository,
        /** Config */config: Config
    ) {
        this.leadRepo = leadRepo;
        this.pageRepo = pageRepo;
        this.config = config;
    }

    async createLead(pageSlug: string, data) {
        const page = await this.pageRepo.findBySlug(pageSlug);
        
        const newLead = await this.leadRepo.create(data)
        newLead.landingPage = page!;
        return await this.leadRepo.save(newLead);        
    }

    async getLeadCounts(userId: number) {
        console.log('GET LEAD COUNTS')
        return this.leadRepo.getCountByLandingPageAndDate();
    }
}