
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    Column,
    Entity,
    ManyToOne,


    PrimaryGeneratedColumn,
    OneToOne,
    JoinColumn,
} from "typeorm";
import { ObjectType, Field, Int, InputType } from "type-graphql";
import Account from './Account';
import User from './User';

@ObjectType()
@InputType('MembershipInput')
@Entity()
export default class Membership extends Database.TimestampedModel {
    // Fields
    @Field()
    @PrimaryGeneratedColumn()
    public id!: number;
    
    
  // @Field()
  // @Column({
  //   nullable: true
  // })
  // public type?: string;  
  
  @Field()
  @Column()
  public active!: boolean;
    
    // Associations
    
      @OneToOne(type => Account, account => account.membership, { cascade: true })
      @JoinColumn()
      account: Account;
      

      @OneToOne(type => User, user => user.membership)
      @JoinColumn() // this decorator is optional for @ManyToOne, but required for @OneToOne
      user: User;
      
}