
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    Column,
    Entity,
    

    PrimaryGeneratedColumn,
} from "typeorm";
import { ObjectType, Field, Int, InputType } from "type-graphql";
import GraphQLJSON from 'graphql-type-json';
import { PageSettings} from 'squeazee-types'


@ObjectType()
@InputType('PaymentInput')
@Entity()
export default class Payment extends Database.TimestampedModel{
    // Fields
    @Field()
    @PrimaryGeneratedColumn()
    public id!: number;
    
  @Field(type => GraphQLJSON)
  @Column({ type: "json" ,nullable: false})
  public token!: PageSettings;
    
    // Associations
    
}