
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    Column,
    Entity,
    OneToMany,


    PrimaryGeneratedColumn,
    OneToOne,
} from "typeorm";
import { ObjectType, Field, Int, InputType } from "type-graphql";
import Account from './Account';

@ObjectType()
@InputType('PlanInput')
@Entity()
export default class Plan extends Database.TimestampedModel{
    // Fields
    @Field()
    @PrimaryGeneratedColumn()
    public id!: number;
    
    
  @Field()
  @Column()
  public active!: boolean;
    

    
  // @Field(type => [String])
  // @Column("text", {array: true})
  // public features?: string[];
    

    
  // @Field()
  // @Column({
  //   nullable: false
  // })
  // public stripe_subscription_id!: string;
    
    // Associations
    
      @OneToOne(type => Account, account => account.plan)
      account: Account;
      
}