
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
  Column,
  Entity,
  OneToMany,


  PrimaryGeneratedColumn,
  OneToOne, RelationId
} from "typeorm";
import { ObjectType, Field, Int, InputType } from "type-graphql";
import Membership from './Membership';
import Authorization from './Authorization';

@ObjectType()
@InputType('UserInput')
@Entity()
export default class User extends Database.TimestampedModel {
  // Fields
  @Field()
  @PrimaryGeneratedColumn()
  public id!: number;


  @Field()
  @Column({
    nullable: false
  })
  public name!: string;



  @Field()
  @Column({
    // nullable: false,
    // unique: true
    nullable: true,
    
  })
  public email!: string;

  // Associations

  @OneToOne(type => Membership, membership => membership.user, { cascade: true })
  membership: Membership;


  // @RelationId((authorization: Authorization) => authorization.user)
  // public userId!: string
  @OneToMany(type => Authorization, authorization => authorization.user, { cascade: true })
  authorizations: Authorization[];

}