
/** 
 * This file generated by Apso.
*/

import {Container} from 'sahara';
import {HttpServer} from '@apso/server';
import FileController from '../controllers/FileController';

export default (container: Container) => {
    const router = container.resolveSync<HttpServer.Router>('PublicRouter');
    const basePath = '/auth';

    router.get('/list', FileController, 'list');
};