
/** 
 * This file generated by Apso.
*/

import {Container} from 'sahara';
import {HttpServer} from '@apso/server';
import LandingPageController from '../controllers/LandingPageController';

export default (container: Container) => {
    const router = container.resolveSync<HttpServer.Router>('PublicRouter');
    const basePath = '/page';

    router.get(`${basePath}/:slug`, LandingPageController, 'getBySlug');
};