
/** 
 * This file generated by Apso.
*/

import {Container} from 'sahara';
import {HttpServer} from '@apso/server';
import LeadController from '../controllers/LeadController';

export default (container: Container) => {
    const router = container.resolveSync<HttpServer.Router>('PublicRouter');
    const basePath = '/lead';

    router.post(`${basePath}/:pageSlug`, LeadController, 'create');
};