
/** 
 * This file generated by Apso.
*/

import {Container} from 'sahara';
import {HttpServer} from '@apso/server';
import PaymentController from '../controllers/PaymentController';

export default (container: Container) => {
    const router = container.resolveSync<HttpServer.Router>('PublicRouter');

    router.get('/list', PaymentController, 'list');
};