
/** 
 * This file generated by Apso.
*/

import {Container} from 'sahara';
import {HttpServer} from '@apso/server';
import UserController from '../controllers/UserController';

export default (container: Container) => {
    const router = container.resolveSync<HttpServer.Router>('PublicRouter');

    router.get('/list', UserController, 'list');
};