
/** 
 * This file generated by Apso.
*/

import {HttpServer} from '@apso/server';
import AccountService from '../services/AccountService';

class AccountController extends HttpServer.BaseController {
    private readonly service: AccountService;

    public constructor(
        /** AccountService */service: AccountService
    ){
        super();
        this.service = service;
    }

    public async list() {
    }

    public async create(){
    }
}

export default AccountController