
/** 
 * This file generated by Apso.
*/

import {HttpServer} from '@apso/server';
import FileService from '../services/FileService';

class FileController extends HttpServer.BaseController {
    private readonly service: FileService;

    public constructor(
        /** FileService */service: FileService
    ){
        super();
        this.service = service;
    }

    public async list() {
    }

    public async create(){
    }
 
}

export default FileController