
/** 
 * This file generated by Apso.
*/

import {HttpServer} from '@apso/server';
import LeadService from '../services/LeadService';

class LeadController extends HttpServer.BaseController {
    private readonly service: LeadService;

    public constructor(
        /** LeadService */service: LeadService
    ){
        super();
        this.service = service;
    }

    public async create(pageSlug: string){
        const { email } = this.req.body;
        const leadData = await this.service.createLead(pageSlug, { email });
        this.sendApiSuccess(leadData)
    }

}

export default LeadController