
/** 
 * This file generated by Apso.
*/

import {HttpServer} from '@apso/server';
import UserService from '../services/UserService';

class UserController extends HttpServer.BaseController {
    private readonly service: UserService;

    public constructor(
        /** UserService */service: UserService
    ){
        super();
        this.service = service;
    }

    public async list() {
    }

    public async create(){
    }
}

export default UserController