
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    EntityRepository,
} from "typeorm";
import Account from "../entities/Account";

@EntityRepository(Account)
export default class AccountRepository extends Database.BaseRepository<Account> {
    public setContext() {
        this.entity = Account;
        this.entityName = 'account';
    }

    public findByEmail(email: string) {
        return this.manager.findOne<Account>(Account, {
            where: {
                email,
            },
        });       
    }   
}