
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    EntityRepository,
} from "typeorm";
import LandingPage from "../entities/LandingPage";

@EntityRepository(LandingPage)
export default class LandingPageRepository extends Database.BaseRepository<LandingPage> {
    public setContext() {
        this.entity = LandingPage;
        this.entityName = 'landing_page';
    }

    public findBySlug(slug: string) {
        return this.manager.findOne<LandingPage>(LandingPage, {
            where: {
                slug,
            },
        });       
    }  
}