
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    EntityRepository,
} from "typeorm";
import Lead from "../entities/Lead";
import LandingPage from '../entities/LandingPage';

@EntityRepository(Lead)
export default class LeadRepository extends Database.BaseRepository<Lead> {
    public setContext() {
        this.entity = Lead;
        this.entityName = 'lead';
    }

    public getCountByLandingPageAndDate() {
        return this.query
            .select('"lead"."landingPageId"', 'landingPageId')
            .addSelect('to_char("lead"."createdAt",\'DD Mon YYYY\')', 'date')
            .addSelect('COUNT(*)', 'count')
            .addSelect('"landingPage"."jsonBody" -> \'name\'', 'title')
            .innerJoinAndSelect(LandingPage, 'landingPage', 'lead."landingPageId" = "landingPage".id')
            .groupBy('"landingPage"."id", "landingPageId", "date"')
            .orderBy('"date", "count"', 'DESC')
            .execute()
        
    }
}