
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    EntityRepository,
} from "typeorm";
import Payment from "../entities/Payment";

@EntityRepository(Payment)
export default class PaymentRepository extends Database.BaseRepository<Payment> {
    public setContext() {
        this.entity = Payment;
        this.entityName = 'payment';
    }
}