
/** 
 * This file generated by Apso.
*/

import { Database } from '@apso/server'
import {
    EntityRepository,
} from "typeorm";
import Plan from "../entities/Plan";

@EntityRepository(Plan)
export default class PlanRepository extends Database.BaseRepository<Plan> {
    public setContext() {
        this.entity = Plan;
        this.entityName = 'plan';
    }
}